name: bci-classifier
channels:
- conda-forge
- default
dependencies:
- python>=3.7
- pip
- numpy>=1.17
- scipy
- matplotlib
- scikit-learn>=0.24
- mne
- tensorflow>=2.2
- pytest
- pytest-mock
- pytest-cov
- pip:
  - -r file:requirements.txt