name: Python Package using Conda

on: [push]

jobs:
  build:
    name: Build on ${{ matrix.os }}, ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9]
        numpy-version: [1.17, 1.18, 1.19, 1.20]
        scipy-version: [1.3, 1.4, 1.5, 1.6]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Miniconda
      # uses: conda-incubator/setup-miniconda@73b9a8098aade40363e43af145303c23542ccb97
      uses: conda-incubator/setup-miniconda@v2.0.1
      with:
        activate-environment: test
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        conda install scipy=${{ matrix.scipy-version }}
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install with pip
      run: |
        pip install -e .[dev]
    - name: Test with pytest
      run: |
        conda install pytest pytest-mock
        pytest -v
